apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ${appname}
  template:
    metadata:
      labels:
        app: ${appname}
    spec:
      containers:
      - name: ${appname}
        image: harishtiru/${appname}:v${BUILD_ID}
        ports:
        - containerPort: 8501
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
